# Server Configuration
server.port=8080

# Application Name
spring.application.name=unsiiyat-backend

# MySQL Database Configuration (Update with your MySQL credentials)
spring.datasource.url=jdbc:postgresql://72.61.229.22:5432/unsiiyat_local
spring.datasource.username=zohaibadmin
spring.datasource.password=ertIU_121
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# HikariCP Connection Pool Configuration
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.validation-timeout=3000
spring.datasource.hikari.keepalive-time=30000

# JWT Configuration
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Cloudflare R2 / S3 Storage Configuration
cloudflare.r2.access-key-id=e22777ff1c5a7a8a6587b8704772f765
cloudflare.r2.secret-access-key=a999414b0be8a81a2a0696aca0f91721199470675c390aefa700591fd5f5b13b
cloudflare.r2.endpoint=https://e371c905c190b33938b543544dd812a0.r2.cloudflarestorage.com
cloudflare.r2.bucket-name=school-erp-bucket
cloudflare.r2.public-url=https://pub-9f970512565f40959b4a3ac757596698.r2.dev


spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

